# Generated by Django 5.1.1 on 2024-11-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_user_is_root_document_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
        ),
    ]
